#!/usr/bin/env pwsh

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Increase Litra brightness
# @raycast.mode silent

# Optional parameters:
# @raycast.needsConfirmation false

# Documentation:
# @raycast.description Increase Litra brightness
# @raycast.icon images/logi-options.icns
# @raycast.author Eric van Wijk
# @raycast.authorURL https://github.com/ericvan

# Lighting
litra-devices --json | ConvertFrom-Json `
                     | Select-Object -First 1 `
                     | Set-Variable litra

litra-on
litra-brightness-lm ([math]::min($litra.brightness_in_lumen + 20,250))
